import 'reflect-metadata'
import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import morgan from 'morgan'
import compression from 'compression'
import rateLimit from 'express-rate-limit'
import dotenv from 'dotenv'

dotenv.config()

const app = express()
const PORT = process.env.PORT || 3001

// ---------------------------------------------------------------------------
// Middleware
// ---------------------------------------------------------------------------
app.use(helmet())
app.use(cors({ origin: process.env.ALLOWED_ORIGINS?.split(',') }))
app.use(compression())
app.use(morgan('dev'))
app.use(express.json())

// Rate-limit the chat endpoint: 60 req/min per API key
const chatRateLimit = rateLimit({
  windowMs: 60 * 1000,
  max: 60,
  keyGenerator: (req) => (req.headers['x-api-key'] as string | undefined) ?? req.ip ?? 'unknown',
  standardHeaders: true,
  legacyHeaders: false,
})
app.use('/api/v1/chat/message', chatRateLimit)

// ---------------------------------------------------------------------------
// Routes — generated by TSOA (`pnpm tsoa` must be run before first start)
// ---------------------------------------------------------------------------
import { RegisterRoutes } from './generated/routes'
RegisterRoutes(app)

// Health check (outside TSOA so it always works)
app.get('/health', (_req, res) => res.json({ status: 'ok' }))

// ---------------------------------------------------------------------------
// Error handler — must come after routes
// ---------------------------------------------------------------------------
import { errorHandler } from './middleware/error.middleware'
app.use(errorHandler)

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------
const start = async () => {
  const { prisma } = await import('./lib/prisma')
  await prisma.$connect()
  console.log('Database connected')

  const { getChannel, closeRabbitMQ } = await import('./lib/rabbitmq')
  getChannel()
    .then(() => console.log('RabbitMQ connected'))
    .catch((err) => console.warn('RabbitMQ unavailable — events will be retried on next publish:', err.message))

  const { startAnalyticsJob } = await import('./jobs/analytics.job')
  startAnalyticsJob()
  console.log('Analytics cron job scheduled')

  const server = app.listen(PORT, () => {
    console.log(`Backend running on http://localhost:${PORT}`)
  })

  const shutdown = async () => {
    server.close()
    await closeRabbitMQ()
    await prisma.$disconnect()
    process.exit(0)
  }

  process.on('SIGINT', shutdown)
  process.on('SIGTERM', shutdown)
}

start().catch(console.error)
